/* eslint-disable */
// This file is automatically generated, do not edit!

import "@atcute/client/lexicons";

declare module "@atcute/client/lexicons" {
  namespace LolAtmogusActivityHistory {
    /** A record representing an application's presence data */
    interface Record {
      $type: "lol.atmogus.activity.history";
      activity: LolAtmogusDefs.ActivityPresence;
      createdAt: string;
    }
  }

  namespace LolAtmogusDefs {
    /** Images for the presence and their hover texts */
    interface ActivityAssets {
      [Brand.Type]?: "lol.atmogus.defs#activityAssets";
      largeImage?: string | null;
      largeText?: string | null;
      smallImage?: string | null;
      smallText?: string | null;
    }
    /** Represents an emoji used for a custom status */
    interface ActivityEmoji {
      [Brand.Type]?: "lol.atmogus.defs#activityEmoji";
      name: string;
      animated?: boolean | null;
      id?: number | null;
    }
    /** Information for the current party of the player */
    interface ActivityParty {
      [Brand.Type]?: "lol.atmogus.defs#activityParty";
      id?: string | null;
      size?: ActivityPartySize | null;
    }
    /** Represents the activity party's current and maximum size */
    interface ActivityPartySize {
      [Brand.Type]?: "lol.atmogus.defs#activityPartySize";
      currentSize: number;
      maxSize: number;
    }
    /** An application's presence data */
    interface ActivityPresence {
      [Brand.Type]?: "lol.atmogus.defs#activityPresence";
      name: string;
      /** Minimum: 0 */
      type: number;
      applicationId?: number | null;
      assets?: ActivityAssets | null;
      details?: string | null;
      emoji?: ActivityEmoji | null;
      party?: ActivityParty | null;
      state?: string | null;
      timestamps?: ActivityTimestamps | null;
      url?: string | null;
    }
    /** Timestamps for the start and/or end of the activity */
    interface ActivityTimestamps {
      [Brand.Type]?: "lol.atmogus.defs#activityTimestamps";
      end?: string | null;
      start?: string | null;
    }
  }

  namespace LolAtmogusGetUserActivity {
    interface Params {
      /** Handle or DID of account to fetch profile of */
      actor: string;
    }
    type Input = undefined;
    interface Output {
      activity: LolAtmogusDefs.ActivityPresence;
    }
  }

  namespace LolAtmogusActivityCurrent {
    /** A record representing a user's current game activity */
    interface Record {
      $type: "lol.atmogus.activity.current";
      activity: LolAtmogusDefs.ActivityPresence | null;
    }
  }

  interface Records {
    "lol.atmogus.activity.history": LolAtmogusActivityHistory.Record;
    "lol.atmogus.activity.current": LolAtmogusActivityCurrent.Record;
  }

  interface Queries {
    "lol.atmogus.getUserActivity": {
      params: LolAtmogusGetUserActivity.Params;
      output: LolAtmogusGetUserActivity.Output;
    };
  }

  interface Procedures {}
}